import {
  ShoppingBag,
  Briefcase,
  PiggyBank,
  Utensils,
  Home,
  Car,
  Film,
  Heart,
  Dumbbell,
  Plane,
  Gift,
  Smartphone,
  Book,
  Moon,
  Dog,
  Scissors,
  Sparkles,
  Construction,
  CalendarClock,
} from "lucide-react";
export const CATEGORIES = [
  { name: "Salary", icon: Briefcase, color: "#54A0FF", type: "INCOME" },
  { name: "Investments", icon: PiggyBank, color: "#5CAB7D", type: "INCOME" },
  { name: "Business", icon: Briefcase, color: "#FF9F43", type: "INCOME" },
  { name: "Freelancing", icon: Briefcase, color: "#FF9F43", type: "INCOME" },
  { name: "Rent", icon: Home, color: "#5ED4F3", type: "INCOME" },

  { name: "Utilities", icon: Home, color: "#5ED4F3", type: "EXPENSE" },
  { name: "Groceries", icon: ShoppingBag, color: "#FF9F43", type: "EXPENSE" },
  { name: "Food", icon: Utensils, color: "#FF6B6B", type: "EXPENSE" },
  { name: "Transportation", icon: Car, color: "#5ED4F3", type: "EXPENSE" },
  { name: "Entertainment", icon: Film, color: "#FF9FF3", type: "EXPENSE" },
  { name: "Healthcare", icon: Heart, color: "#FD7272", type: "EXPENSE" },
  { name: "Fitness", icon: Dumbbell, color: "#6C5CE7", type: "EXPENSE" },
  { name: "Travel", icon: Plane, color: "#1DD1A1", type: "EXPENSE" },
  { name: "Gifts", icon: Gift, color: "#FF6B6B", type: "EXPENSE" },
  { name: "Gadgets", icon: Smartphone, color: "#54A0FF", type: "EXPENSE" },
  { name: "Education", icon: Book, color: "#FF9FF3", type: "EXPENSE" },
  { name: "Other", icon: Moon, color: "#FF9F43", type: "EXPENSE" },
  { name: "Pet", icon: Dog, color: "#FD7272", type: "EXPENSE" },

  { name: "Clothing", icon: ShoppingBag, color: "#FF2F43", type: "EXPENSE" },
  { name: "Rent", icon: Home, color: "#5ED4F3", type: "EXPENSE" }, // This Rent is for expense
  { name: "Insurance", icon: PiggyBank, color: "#5CAB7D", type: "EXPENSE" },
  { name: "Cosmetic", icon: Sparkles, color: "#FF66C4", type: "EXPENSE" },
  { name: "Personal Care", icon: Scissors, color: "#7158e2", type: "EXPENSE" },
  {
    name: "Home Improvement",
    icon: Construction,
    color: "#3b3b98",
    type: "EXPENSE",
  },
  {
    name: "Subscription",
    icon: CalendarClock,
    color: "#FF6B6B",
    type: "EXPENSE",
  },
];
