import {
  ShoppingBag,
  Briefcase,
  PiggyBank,
  Utensils,
  Home,
  Car,
  Film,
  Heart,
  Dumbbell,
  Plane,
  Gift,
  Smartphone,
  Book,
  Moon,
  Dog,
} from "lucide-react";
export const CATEGORIES = [
  { name: "Salary", icon: Briefcase, color: "#54A0FF" },
  { name: "Investments", icon: PiggyBank, color: "#5CAB7D" },
  {
    name: "Business",
    icon: Briefcase,
    color: "#FF9F43",
  },
  { name: "Freelancing", icon: Briefcase, color: "#FF9F43" },
  { name: "Rent", icon: Home, color: "#5ED4F3" },

  { name: "Utilities", icon: Home, color: "#5ED4F3" },
  { name: "Groceries", icon: ShoppingBag, color: "#FF9F43" },
  { name: "Food", icon: Utensils, color: "#FF6B6B" },
  { name: "Transportation", icon: Car, color: "#5ED4F3" },
  { name: "Entertainment", icon: Film, color: "#FF9FF3" },
  { name: "Healthcare", icon: Heart, color: "#FD7272" },
  { name: "Fitness", icon: Dumbbell, color: "#6C5CE7" },
  { name: "Travel", icon: Plane, color: "#1DD1A1" },
  { name: "Gifts", icon: Gift, color: "#FF6B6B" },
  { name: "Gadgets", icon: Smartphone, color: "#54A0FF" },
  { name: "Education", icon: Book, color: "#FF9FF3" },
  { name: "Other", icon: Moon, color: "#FF9F43" },
  { name: "Pet", icon: Dog, color: "#FD7272" },

  {
    name: "Clothing",
    icon: ShoppingBag,
    color: "#FF2F43",
  },
  {
    name: "Rent",
    icon: Home,
    color: "#5ED4F3",
  },
  {
    name: "Insurance",
    icon: PiggyBank,
    color: "#5CAB7D",
  },
];
